{% set name = "hapiclient" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hapiclient-{{ version }}.tar.gz
  sha256: fcdc47c1786ed1a8b6607d137ccff9b85810399f78fbb866e38065ce4a475351

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - isodate >=0.6.0
    - urllib3
    - joblib
    - pandas >=0.23
    - numpy >=1.14.3

test:
  imports:
    - hapiclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/hapiclient/
  summary: Interface to Heliophysics data server API
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dstansby
